### ISSUE TITLE
Error: Roles do not match in cross cluster search for version 1.12.0

### ISSUE THREAD

**Issue by SitoRBJ** [opensearch-project/security#1032]
Hello everyone,

We have detected the following behavior:

In Open Distro version 1.11.0 the roles of a coordinating environment matched the roles of the remote environments, being possible that a user of the coordinating environment could perform cross searches while his role was present in the remote environment. Example: 

Coordinating cluster: 
- user: mike
- role: custom_admin

Remote cluster:
- role: custom_admin

In this case, Mike can access from the coordinating cluster to the remote cluster as the role is the same in both clusters. 

In Open Distro version 1.12.0 this does not work. Having the same configuration:

Coordinating cluster: 
- user: mike
- role: custom_admin

Remote cluster:
- role: custom_admin

![image](https://user-images.githubusercontent.com/8913336/107634984-b4c3dc00-6c6a-11eb-83aa-dc5ee99ab3fc.png)

![image](https://user-images.githubusercontent.com/8913336/107635213-108e6500-6c6b-11eb-9667-cbc725514c8b.png)

We have found that works by matching per user: 

Coordinating cluster: 
- user: mike
- role: custom_admin

Remote cluster:
- user: mike
- role: custom_admin_2

Amazingly, this works. In this case, Mike can access the remote cluster because the user is matched. Note that the password does not matter and the role that applies is remote(role: custom_admin_2).

We have also verified that the following configuration is valid: 

Coordinating cluster: 
- user: mike; backend_role -> coordinating_admin_custom

Remote cluster:
- role: custom_admin; backend_role -> coordinating_admin_custom

If we assign to a user of the coordinating cluster a backend_role (something that cannot be done from the security interface in Kibana) that also exists in the desired role of the remote cluster, it works.

We have not found anything in the documentation or in the changelog of version 1.12.0 that explains this behavior, so it seems to be an **error**.

Regards

**Comment by SitoRBJ** [comment]
Any update on this?

**Comment by saikaranam-amazon** [comment]
Permission evaluation happens local to the cluster based on the roles associated with the user.

For cross cluster requests, user(with backendroles obtained from authentication backend) is passed in the request from local cluster to the remote cluster and 
the remote cluster gets all the roles associated with this user (locally) and evaluates the permissions. 

In the above case, 

**Case 1** - With just cusotom_admin role and no user at remote cluster

the behavior observed in 1.12 is valid. I tried to reproduce the behavior observed in 1.11 and the request failed with security exception. (which is valid behavior and same as 1.12)

At co-ordintating cluster
 - Created a user `testadmin`
 - Created and asssociated `indices_all` permissions to `same_role` in co-ordinating cluster
 - `same_role` is mapped to `testadmin` in co-ordinating cluster

At remote cluster
 - Created and associated `indices_all` permissions to `same_role` in remote cluster
 - (No testadmin user here)


**Case 2** - With same user but different roles - This is valid behavior and from above issue description as well, there is no regression in 1.11 and 1.12.
 - Here, based on the user plugin gets all the roles associated locally (in the remote cluster) and if these roles have sufficient privileges the request goes through.

**Case 3** - With backend roles same in both cluster - a valid behavior and from above issue description as well, there is no regression in 1.11 and 1.12.
 - Here, based on the user in the request and the associated backend roles, the plugin(at remote) gets the roles mapping to the backend roles. if these roles have sufficient privileges the request goes through.
 
 Let me know, If I am missing anything to reproduce case 1

**Comment by Phandora** [comment]
Hi @saikaranam-amazon

I am facing the same problem as @SitoRBJ. This works on Open Distro 1.11 version, but fails in Open Distro 1.12.

## Steps to reproduce case 1 (cross-cluster search in 1.11 version)

- **Configure remote cluster**
Both, the coordinating and the remote cluster use the following images:
  - **Elasticsearch image**: `amazon/opendistro-for-elasticsearch:1.11.0`
  - **Kibana image**: `amazon/opendistro-for-elasticsearch-kibana:1.11.0`

- **Create index patterns of remote clusters in the coordinating one**

This step can be performed without any issues in Open Distro 1.11 version, however, in 1.12 one it seems to be bugged.
[Cannot create Index Patterns of remote clusters [Open Distro 1.12]](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/688). I hope you can work on it soon.

- **Create an user in the coordinating cluster**

I created the user `William` in the **coordinating cluster** and mapped it to the `all_access` role. **The user William does not exist in the remote cluster**.

![image](https://user-images.githubusercontent.com/33484080/108508379-04825300-72bc-11eb-85f0-152e0b17c6ed.png)

- Coordinating cluster:

>user: William
role: all_access

- Remote cluster:

>role: all_access

- **Go to discover**

![image](https://user-images.githubusercontent.com/33484080/108508282-dc92ef80-72bb-11eb-90ea-19faec341ae9.png)

Cross-cluster searches can be performed correctly. However, in Open Distro 1.12 version when using this same configuration, we got a **Forbidden error**. If this is the expected behavior, why has it not been included in the changelog?

**Comment by saikaranam-amazon** [comment]
Tried to reproduce the behavior using 1.11 clusters as mentioned in the previous comment.
I was unable to search the index patterns from co-ordinating cluster (same behavior as 1.12)

@SitoRBJ @Phandora 
- Were there any backend roles associated with the users that are shared between the two clusters?
- Could you verify your cluster security configuration with the setup used below? 

Images used:
- amazon/opendistro-for-elasticsearch:1.11.0
- amazon/opendistro-for-elasticsearch-kibana:1.11.0

Setup:
 - Remote cluster
   - Single ES node and Kibana node
   - Security 
     - User: `testadmin1` mapped to all_access role  
 - Coordinating cluster
   - Single ES node
   - Security
     - only role all_access is present (and no `testadmin1` present)
  

Screenshots:
`testadmin1` role mapping to `all_access`
<img width="1264" alt="testadmin1_role_mapping" src="https://user-images.githubusercontent.com/71428218/108701864-8083d180-752e-11eb-958d-f1d842ecdfd5.png">

Index pattern search with `testadmin1`
<img width="1079" alt="index_pattern_testadmin1" src="https://user-images.githubusercontent.com/71428218/108701945-9beedc80-752e-11eb-9679-004528242bbc.png">

Index pattern search with `admin`
<img width="1087" alt="index_pattern_admin" src="https://user-images.githubusercontent.com/71428218/108701999-ae691600-752e-11eb-904e-777ef8880a90.png">

**Comment by Phandora** [comment]
Hi @saikaranam-amazon

My environment configuration may have not been detailed enough. I have two environments, both of them, with a single ES node and a Kibana node.

- **Images used**:

  - amazon/opendistro-for-elasticsearch:1.11.0
  - amazon/opendistro-for-elasticsearch-kibana:1.11.0

However, one of these environments has been configured as a remote cluster in the other environment, so it can be accessed from its own kibana and from the coordinating cluster's kibana.

|Coordinating cluster|Remote cluster|
|---|---|
|single ES node: 1.11.0 version|single ES node: 1.11.0 version|
|Kibana node: 1.11.0 version|Kibana node: 1.11.0 version|
|**User: testadmin1** (mapped to all_access role)|**User: the testadmin1 user does not exists**|
|**Role: all_access**|**Role: all_access**|

>The all_access role exits in both environments, but the testadmin1 user only exists in the coordinating one.

<details>
<summary>Coordinating cluster security configuration</summary>

- **Users**:

![image](https://user-images.githubusercontent.com/33484080/108722827-da32ce80-7523-11eb-922a-b3d1a358ca1c.png)

- **Roles**:

![image](https://user-images.githubusercontent.com/33484080/108723287-5f1de800-7524-11eb-962a-2c428d55291f.png)

</details>


<details>
<summary>Remote cluster security configuration</summary>

- **Users**:

![image](https://user-images.githubusercontent.com/33484080/108723131-372e8480-7524-11eb-99b9-69a18a0c04e0.png)

- **Roles**:

![image](https://user-images.githubusercontent.com/33484080/108723193-46adcd80-7524-11eb-9852-66b8c33cc604.png)

</details>

When accessing **from the coordinating cluster's kibana** using the `testadmin1` it works without any issues since the `all_access` role exists in both clusters:

- **Creating index pattern for the remote cluster** in the coordinating cluster's kibana (This index pattern is just an example to explain the issue):

![image](https://user-images.githubusercontent.com/33484080/108721481-55938080-7522-11eb-8a0e-cde5668d3eb0.png)

- **Accessing discover**:

![image](https://user-images.githubusercontent.com/33484080/108722082-0732b180-7523-11eb-8009-3c604900615c.png)

However, it fails in 1.12 version. It is also related to the issue: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/688

**Comment by Phandora** [comment]
Any update on this?

**Comment by Phandora** [comment]
This issue seems to be also related: https://discuss.opendistrocommunity.dev/t/cross-cluster-search-with-secured-clusters/5162.

They said it fails on `1.12.0`, `1.13.0` and `1.13.1` 🤕

**Comment by jesuslinares** [comment]
Hi,

This issue is currently impacting our production deployments. Did you get a chance to review it?

Thanks.

**Comment by Phandora** [comment]
Hi!

It keeps failing on `1.13.2` version. Any update on this?

regards

**Comment by davidlago** [comment]
We've received reports of this being fixed in 1.13.2. @Phandora if this is not resolved for you, could you please provide additional repro details to help us troubleshoot?

Additionally, [we strongly recommend migrating to OpenSearch](https://opendistro.github.io/for-elasticsearch/blog/2021/12/the-future-of-open-distro/) as that is where we are fixing security issues and others moving forward. Thanks!
