### ISSUE TITLE
install_demo_configuration.sh won't run if elasticsearch.yml contains lines with "opendistro_security"

### ISSUE THREAD

**Issue by starcatter** [opensearch-project/security#1108]
It won't run because inside my elasticsearch.yml file I have
`# opendistro_security.disabled: true`

After hours of trying to figure out what went wrong I found this in [install_demo_configuration.sh](https://github.com/opendistro-for-elasticsearch/security/blob/c0b1bacc923891c43d92365d48585bd2ff55b7ec/tools/install_demo_configuration.sh#L189)
`
if $SUDO_CMD grep --quiet -i opendistro_security "$ES_CONF_FILE"; then
  echo "$ES_CONF_FILE seems to be already configured for Security. Quit."
  exit $skip_updates
fi
`

IMO this is a valid issue, it's not unusual during testing to have a config file with commented out lines for commonly used options, and the main use case for install_demo_configuration.sh is for testing/learning. Having commented out options alter the behavior of the docker container was confusing.

My suggested solution is to add another option to ignore this check and use it in docker-entrypoint.sh. Something like 
` -x ignore existing opendistro_security config entries`

**Comment by cliu123** [comment]
@starcatter `install_demo_configuration.sh` is used to generate all required TLS certificates and add the Security Plugin Configuration to your `elasticsearch.yml` file. When those configurations have already existed in your `elasticsearch.yml` file, the script is expected not to duplicate the existing configurations. This is the whole point of [the check](https://github.com/opendistro-for-elasticsearch/security/blob/c0b1bacc923891c43d92365d48585bd2ff55b7ec/tools/install_demo_configuration.sh#L189). If the comments containing `opendistro_security` is not a must-have, I'd suggest to remove them. Otherwise, please feel free to reopen the issue. Thanks!

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
