### ISSUE TITLE
Kibana index patterns & Custom Roles

### ISSUE THREAD

**Issue by mkiran18** [opensearch-project/security#142]
Hi @aetter ,

Kibana is not displaying any data for a pattern match, But works fine when full index name is selected under **Management** -> **Index Patterns**

role: 
```
{
  "index_permissions": [
    {
      "index_patterns": [
        "index1-45673-*"
      ],
      "dls": "",
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "read",
        "kibana_all_read"
      ]
    }
  ],
  "tenant_permissions": [],
  "cluster_permissions": []
}
```
role mapping:
```
{
  "backend_roles": [],
  "hosts": [],
  "users": [
    "user"
  ]
}
```
user:

```
{
  "backend_roles": [
    "user-role",
    "kibanauser"
  ],
  "attributes": {},
  "password": ""
}

```
Kibana Index Patterns:

Below are the two kibana index patterns

1. index1-45673-item1-2019-09-20  : Works fine
2. index1-\*-\*-\*     : failes with error : Discover: no permissions for [indices:data/read/search] and User [name=user, roles=[user_role, kibanauser], requestedTenant=null]

Wild Card Pattern is not able to match to the index that role has permission to, but works fine with the exact index name.

Thanks

**Comment by aetter** [comment]
Hey @mkiran18, I'm actually not able to reproduce. Can you double-check the role and mapping?

On a more meta note, I'd recommend against tagging me on new issues unless it's specifically something that I've worked on. Other people on the team and in the community might assume that I'm "on it" and not chime in with more better, more timely information than I can provide. 😃 

My role mapping

```json
{
    "new-role": {
        "reserved": false,
        "hidden": false,
        "backend_roles": [],
        "hosts": [],
        "users": [
            "new-user"
        ],
        "and_backend_roles": []
    }
}
```

My role

```json
{
    "new-role": {
        "reserved": false,
        "hidden": false,
        "cluster_permissions": [],
        "index_permissions": [
            {
                "index_patterns": [
                    "index1-*-*-*"
                ],
                "dls": "",
                "fls": [],
                "masked_fields": [],
                "allowed_actions": [
                    "read",
                    "kibana_all_read"
                ]
            }
        ],
        "tenant_permissions": [],
        "static": false
    }
}
```

My user

```json
{
    "new-user": {
        "hash": "",
        "reserved": false,
        "hidden": false,
        "backend_roles": [],
        "attributes": {},
        "static": false
    }
}
```

The following queries all return results:

```
GET index1-*-*-*/_search
GET index1-45673-item1-2019-09-20/_search
GET index1-45673-*/_search
GET index1-45673-**/_search
```

**Comment by mkiran18** [comment]
Hi @aetter ,

Apologies for tagging, i see that you are very active in security space of OD thought of tagging for quick check.

to your point , the issue is not with elasticsearch API. This is happening in kibana only.

Error when used a * as patterns , happen with index1-\*-\*-\*  as well.
![image](https://user-images.githubusercontent.com/30534081/65451385-ecbb4c80-ddf3-11e9-9f8f-d0d191e4c2f0.png)

With full index name rather than pattern : no issues and data is displayed.

![image](https://user-images.githubusercontent.com/30534081/65451603-5c313c00-ddf4-11e9-9d01-48218ad5c3f9.png)

The expectation is kibana will auto filter all other indices where the loggedin-user do not have permission to.

very similar to:  https://discuss.elastic.co/t/kibana-defining-access-to-multi-customers-sharing-same-dashboard/158567

this was used in elasticsearch+kibana before , trying to replicate the same behaviour on Open Distro as well.

Thanks

**Comment by aetter** [comment]
Ah, I think I see. So the expected behavior here is that the security plugin filters out any indices that a) match your pattern and b) you don't have access to prior to performing the search? Is the description below an accurate summary of your concern?

Steps to reproduce:

1. New role, index permissions of `index1-45673-*`, action group `read`, save.
1. New user.
1. Map new role to new user.
1. Map `kibana_user` to new user.
1. Create two indices:

   ```json
   PUT index1-45673-app1-2019-09-23/_doc/1
   {"some document": "and its data"}
   ```

   ```json
   PUT index1-78965-app2-2019-09-23/_doc/1
   {"some document": "and its data"}
   ```

1. Log in to Kibana as the new user.
1. Dev tools

   ```
   GET index1-45673-*/_search
   ```

   Success.

   ```
   GET index1-78965-*/_search
   ```

   Expected failure.

   ```
   GET index1-*/_search
   ```

   Failure. Expected behavior is that the search would still find documents in `index1-45673-app1-2019-09-23`, which the user has permissions to.

**Comment by mkiran18** [comment]
Yup.... thats exactly what i am trying to achieve :)

I have followed the steps what i have done for xpack + elasticsearch, I am not sure if there are any different steps for Open distro as the security plugin is different in this case. 

Thanks in advance.

**Comment by aetter** [comment]
Roger that. I'm worried that there's some fundamental architectural decision that explains why this feature doesn't work the way we expect, but I'll leave it to the development team to confirm/deny and classify as a bug or as-designed.

Adding @hardik-k-shah and @elfisher for their thoughts.

**Comment by mkiran18** [comment]
Thanks .,., This feature enables to have one kibana/elastic index pattern for all the users but still have control on what they see based on the roles.

Otherwise we will have many different patterns in the kibana -> discover, Index pattern dropdown and when users switch they will see the error 

![image](https://user-images.githubusercontent.com/30534081/65466351-66166780-de13-11e9-9a29-999a914e1be6.png)

And to mention maintenance of them is a tedious process.

**Comment by mkiran18** [comment]
Hi, Any update ? just wanted to know if this is as per design or actually an issue.

**Comment by kryadov** [comment]
The same issue with  No permissions for ... No index-level perm match for User [name= ... in  elasticsearch.log. Opendistro 1.2.0.

**Comment by bittu664** [comment]
yes, its an issue, simply by going to role server and add the index pattern which you want to show. just like this here ...
![kibana](https://user-images.githubusercontent.com/28609215/69476897-9d01fd00-0e05-11ea-802c-3244e3166554.png)

**Comment by vrozov** [comment]
It is an expected behavior that when a kibana index pattern or a query pattern includes one or more indices that a user does not have necessary permission(s), the query fails with security exception. Note that security plugin does not do any query re-write and submits the original query pattern to ES for execution. Should that pattern include any index that the user does not have permission(s) for, it would be a security violation. It will be an enhancement request to support query re-write and I am not even sure that it is possible in all cases as an intersection of a query pattern and indices with granted permissions may be a disjoin set not easily expressed by a single index or by another index match pattern.

**Comment by mkiran18** [comment]
Hi @vrozov , Thats an issue when we create one index pattern in kibana for shared users on the same tenancy . We ended up creating a lot of index patterns as work around to this security limitation and had to educate the users to switch to their specific pattern upon login.

Thanks for looking in to it.

**Comment by vrozov** [comment]
@mkiran18 roger-that. This is current design limitation and, afaik, there are no other workarounds other than to define different index patterns for different roles. Possibly kibana plugin can help by limiting user access to their specific index pattern(s).

Instead of query re-write we may try to filter out all documents for indices that a user does not have permission for during query execution, but that may impact performance, so we will have to see what option is the best. In any case, likely we will have to provide a configuration settings that will enable new behavior and keep the old behavior for users that are not affected by that limitation or prefer old behavior for any reason.

**Comment by vrozov** [comment]
There seems to be an option to enable the desired behavior. Please see `do_not_fail_on_forbidden` in [kibana multi-tenancy](https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/multi-tenancy/)

**Comment by micheljung** [comment]
I'm not sure if I'm experiencing the same or a different issue. I have a role like so:

```
my_role:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster_composite_ops_ro"
  index_permissions:
    - index_patterns:
        - "logstash-*"
      allowed_actions:
        - "read"
  tenant_permissions:
    - tenant_patterns:
        - "global_tenant"
      allowed_actions:
        - "kibana_all_read"
  static: false
```

and plenty of indices like:
```
logstash-myapp-2021-01.25
logstash-myapp-2021-01.26
logstash-myapp-2021-01.27
```

In the Global tenant, i create an index pattern like so:

TODO add screenshot

I expect that the user sees all of them. However, the user sees nothing:

TODO add screenshot

When I change the permissions to:

```
  index_permissions:
    - index_patterns:
        - "*"
```

it works:

TODO add screenshot

**Comment by DanielHabenicht** [comment]
@vrozov is right. 

In order to ignore indices the user has no permission to you can set `do_not_fail_on_forbidden: true` in your `plugins/opendistro_security/securityconfig/config.yml`

**Comment by davidlago** [comment]
Closing as `do_not_fail_on_forbidden` addresses this issue's use case.
