### ISSUE TITLE
Permissions for Kibana user

### ISSUE THREAD

**Issue by er1z** [opensearch-project/security#158]
I'm pretty new to ODFE and started to configuring whole stack.

I deployed it using Docker, created custom certificates and everything seems to be working.

But now I'm struggling with permission restriction for Kibana connection account. What are minimum required permissions/roles in order to Kibana not showing a message `Kibana not ready yet`? Tried to map a custom user to `kibanaserver` roles and almost everything related that I found in docs.

Of course, I've updated permissions using a script from `tools`.

**Comment by iv-shamanow** [comment]
I have the same issue. Kibana cannot start when used any custom user instead of `kibanauser` (except for administrator accounts with access to everything in elasticsearch). It seems that OpenDistro has some hidden/hardcoded permissions for `kibanaserver` user only.

**Comment by deadNightTiger** [comment]
There is a static role named `kibana_server` (with underscore), you can see it here: https://github.com/opendistro-for-elasticsearch/security/blob/v1.2.0.0/src/main/resources/static_config/static_roles.yml#L76

The demo user `kibanaserver`, as defined in `roles_mapping.yml`, is mapped to that role.

**Comment by iv-shamanow** [comment]
> The demo user kibanaserver, as defined in roles_mapping.yml, is mapped to that role.

The problem is you cannot change user in this mapping. 
If I understand docs correctly, this should work:
- create another user (for example `kibana_internal`) in `internal_users.yml`
- include this user in `roles_mapping.yml` for `kibana_server` 
- apply configuration through `securityadmin.sh`

But I still get dead Kibana and errors in logs like `[security_exception] no permissions for [indices:admin/get] and User [name=kibana_internal, roles=[], requestedTenant=null]`.

**Comment by alexz00** [comment]
Hi, it seems I'm facing the very same issue.

I created a _kib_ user and added the mapping to the _kibana_server_ role. If I query the role mappings I get:

`"kibana_server" : {
    "reserved" : false,
    "hidden" : false,
    "backend_roles" : [ ],
    "hosts" : [],
    "users" : [
      "kib"
    ],
    "and_backend_roles" : [ ]
  }`

But when I start Kibana it fails:

> [security_exception] no permissions for [indices:admin/get] and User [name=kib, roles=[], requestedTenant=null] :: {"path":"/.kibana","query":{},"statusCode":403,"response":"{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"no permissions for [indices:admin/get] and User [name=kib, roles=[], requestedTenant=null]\"}],\"type\":\"security_exception\",\"reason\":\"no permissions for [indices:admin/get] and User [name=kib, roles=[], requestedTenant=null]\"},\"status\":403}"}

Can you please help?

Thanks.

**Comment by BlackMetalz** [comment]
up

**Comment by Ultraseamus** [comment]
FWIW: I was seeing this same issue:

`Unable to connect to Elasticsearch. Error: [security_exception] no permissions for [indices:admin/get] and User [name=kibanaserver, backend_roles=[], requestedTenant=null]`

I eventually took a look at the static role to see what permissions it had:

```
- index_patterns:
    - ".kibana"
    allowed_actions:
    - "indices_all"
  - index_patterns:
    - ".kibana-6"
    allowed_actions:
    - "indices_all"
  - index_patterns:
    - ".kibana_*"
    allowed_actions:
    - "indices_all"
```

And noticed that the Kibana index name I was using did not fit into any of those patterns. For me, switching the index name to one of those got me past the above error. Which I guess means the error was actually just about Kibana not being able to read from its own management index. Rather than the cluster-wide index permissions I assumed it was lacking.

Hopefully that helps others.

**Comment by mr-snow2** [comment]
Did you try updating the new kibana user name under server_username field in config.yml?

**Comment by pawelw1** [comment]
@er1z Have you found a solution to your issue? 

If you'd like to change the default `kibanaserver` user to a custom one, first assign `kibana_server` role to that user.

![image](https://user-images.githubusercontent.com/87704213/145413661-b5c223ab-5d54-4e8d-b5de-e92c240c0240.png)

Next, change the value of the `server_username` key in `config.yml` to match your custom user name. As per documentation, the default value is `kibanaserver`.

![image](https://user-images.githubusercontent.com/87704213/145414000-50372a1e-24da-4ab4-9db2-26198bf21848.png)

ODFE: 
https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/multi-tenancy/#configuration

OpenSearch:
https://opensearch.org/docs/latest/security-plugin/access-control/multi-tenancy/#configuration

**Comment by er1z** [comment]
It was pretty long time ago, unfortunately. Don't remember, the only thing was some certificate issue or sth.

**Comment by pawelw1** [comment]
@er1z thanks for the update.

**Comment by cliu123** [comment]
`kibana_user` is the role that you need.
