### ISSUE TITLE
[BUG] Parsing of plugins.security.authcz.admin_dn

### ISSUE THREAD

**Issue by ohdearaugustin** [opensearch-project/security#1640]
**Describe the bug**
Somehow the order of the certificate subject in plugins.security.authcz.admin_dn matter.
```
plugins.security.authcz.admin_dn:
- "L=Graz,ST=Organisation Opensearch,CN=ADMIN"
```
is not the same as
```
plugins.security.authcz.admin_dn:
- "CN=ADMIN,ST=Organisation Opensearch,L=Graz"
```
with the second configuration the authentication will fail.

**To Reproduce**
1. Create a certificate with following subject "CN=ADMIN,ST=Organisation Opensearch,L=Graz" 
2. Verify the subject with openssl ```openssl x509 -in admin.pem -noout -text```
3. The subject should be ``` Subject: CN = ADMIN, ST = Organisation Opensearch, L = Graz```
4. Add 
```
plugins.security.authcz.admin_dn:
- "CN=ADMIN,ST=Organisation Opensearch,L=Graz"
``` 
to your opensearch.yml
5. Try to use the securityadmin.sh
6. See error
```
Will connect to localhost:9300 ... done
Connected as L=Graz,ST=Organisation Opensearch,CN=ADMIN
ERR: L=Graz,ST=Organisation Opensearch,CN=ADMIN is not an admin user
Seems you use a client certificate but this one is not registered as admin_dn
Make sure opensearch.yml on all nodes contains:
plugins.security.authcz.admin_dn:
  - "L=Graz,ST=Organisation Opensearch,CN=ADMIN"
```

**Expected behavior**
The order of the certificate subject should be irrelevant.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: docker-container
 - Version opensearchproject/opensearch:1.2.4

**Comment by peternied** [comment]
@ohdearaugustin Thanks for filing this issue and providing the detailed repro.

**Comment by ohdearaugustin** [comment]
@peternied What kind of details would you need? For me it is pretty clear.

**Comment by peternied** [comment]
I am not sure of your question, I do not think any additional details are needed on this issue.

**Comment by ohdearaugustin** [comment]
@peternied Sorry had a long day and just misread your comment.^^

**Comment by peternied** [comment]
@ohdearaugustin No worries, have a restful evening.

**Comment by cwperks** [comment]
I did a little more digging on this issue to understand why the re-arranged distinguished name (dn) was reporting an error.

`opensearch-security` uses `LdapName` from `javax.naming.ldap`. See https://github.com/opensearch-project/security/blob/f431ec2201e1466b7c12528347a1f54cf64387c9/src/main/java/org/opensearch/security/configuration/AdminDNs.java#L144.

`.contains` uses `.equals` under the hood and here's the implementation of `.equals` in openjdk-11 for `LdapName`: https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.naming/share/classes/javax/naming/ldap/LdapName.java#L669

Upon testing this the rdns come back in the order they are parsed.

i.e. `CN=node-0.example.com,OU=node,O=node,L=test,DC=de`

is parsed as rdn list of `Rdns: [DC=de, L=test, O=node, OU=node, CN=node-0.example.com]`

Since the re-arranged DN is of a different order the `.equals` method of `LdapName` returns false. 

Some components of a DN like DC (Domain Component) and OU (Organizational Unit) need to keep their order [preserved](https://www.ibm.com/docs/en/ibm-mq/7.5?topic=certificates-distinguished-names) and cannot be re-ordered without changing the meaning. If this change is desired then I would think it would be best to do this inside `javax`.
