### ISSUE TITLE
[UX/UI] own_index role is required to make index_pattern based permissions work

### ISSUE THREAD

**Issue by ronniepg** [opensearch-project/security#1860]
**What is the bug?**
A role giving permissions based on index pattern does not grant the user the specified permissions unless the own_index role is additionally provisioned for that user.

**How can one reproduce the bug?**
1. Create an internal role like so 
`
curl -XPUT https://localhost:9200/_plugins/_security/api/roles/sem-role -H 'Content-Type: application/json' -d'
{
  "cluster_permissions": [
    "cluster_monitor"
  ],
  "index_permissions": [{
    "index_patterns": [
      "sem*"
    ],
    "allowed_actions" : ["*"]
  }]
}
`
2. Create a user with this role
`
curl -XPUT https://localhost:9200/_plugins/_security/api/internalusers/sem-user   -H 'Content-Type: application/json' -d'
{
  "password": "######",
  "opendistro_security_roles": ["sem-role"]
}
'
`
3. Index document using this user
`
curl -u sem-user -X POST "https://localhost:9200/sem1234/_doc/1?pretty" -H 'Content-Type: application/json' -d'
{
  "@timestamp": "2000-11-15T13:12:00",
  "message": "test",
  "user": {
    "id": "abcd"
  }                         
}                            
'
`
Response:
`
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "no permissions for [indices:data/write/bulk] and User [name=sem-user, backend_roles=[], requestedTenant=null]"
      }
    ],
    "type" : "security_exception",
    "reason" : "no permissions for [indices:data/write/bulk] and User [name=sem-user, backend_roles=[], requestedTenant=null]"
  },
  "status" : 403
}
`

NOTE:
- adding the own_index role to this user resolved the permission issue!
- there are certain APIs such as CREATE INDEX API which work fine (i.e. respecting the defined index pattern) even without adding the own_index role to the user.

**What is the expected behavior?**
The index permissions based on patterns should work fine without having to add the own_index role to the user.

**What is your host/environment?**
OpenSearch 1.2.4 with opensearch-security plugin enabled on OEL7

**Do you have any screenshots?**
NA

**Do you have any additional context?**
Discussed here https://forum.opensearch.org/t/internal-user-not-able-to-perform-operations-based-on-internal-role/9529/4

**Comment by cliu123** [comment]
@ronniepg `own_index` static role is by default mapped to every user. Was the rolesmapping intentionally removed?

**Comment by ronniepg** [comment]
@cliu123 Well i had cleaned up all the demo users/roles/role-mappings and added only those user/role which were required. The own_index was also cleanup since its significance wasnt mentioned anywhere.

Why do we need own_index role to make a simple role like the one mentioned above work? I would expect each role to be independent of another role in a typical RBAC model.

If this own_index role is expected to be always present, shouldnt it be part of the code rather than a role mapping which can get cleaned up?

**Comment by rockybean** [comment]
Also met an issue with this `own_index` role. We have some username starting with `_` and this will cause exceptions as below when try to bulk write.
```
"cause": {
                "type": "invalid_index_name_exception",
                "reason": "Invalid index name [_x], must not start with '_'.",
                "index": "_xxxx",
                "index_uuid": "_na_"
            }
```

**Comment by scrawfor99** [comment]
[Triage] Flagging this as a UX issue; keeping in the backlog.

**Comment by scrawfor99** [comment]
I don't think this issue is relevant anymore. Please open a new issue if further trouble arises.

**Comment by pegtrifork** [comment]
I encountered the issues mentioned here, now using OpenSearch and OpenSearch Dashboard 2.11.1.

When trying to sign in to the OpenSearch Dashboard with a username starting with `_` you are unable to enter the dashboard, and is instead greeted with the invalid_index_name_exception error instead.

It seems like this is because the dashboard is trying to validate all of your roles on login and faces an error if `own_index` is applied to this user (via the `*` wildcard).

I tried removing the `own_index` role mapping, and validate that everything still works.
Creating an index pattern was now broken.
It seems like this is due to the cluster_permission `cluster_composite_ops` which is granted via the `own_index` role, and is not related to the index part of that role.

The issue therefore seems to be two-fold.
* The role of `own_index` and why it is there by default is not clear.
* When signing in to the Dashboard all roles are validated even though they are never used. (This issue may not be for this Repo, but this seems related, so posting here for now.)
