### ISSUE TITLE
standalone plugin missing deps

### ISSUE THREAD

**Issue by nikhil-bhat** [opensearch-project/security#202]
Standalone security plugin includes securityadmin.sh which calls the OpendistroSecurityAdmin java class.
The classpath of the tool is "$DIR/../*:$DIR/../../../lib/*:$DIR/../deps/*"
This tool expects it to be installed in the plugins directory of elasticsearch and cannot be used independently .
Please release a standalone version which bundles /usr/share/elasticsearch/libs in the deps directory with it so that the tools can be used independently.

**Comment by nateynateynate** [comment]
Hi @nikhil-bhat ! 

A reasonable request! However, since the time of your writing, OpenSearch has  superseded the OpenDistro project. OpenSearch and  the plugins are now distributed together - independent plugin releases aren't necessary. 

Please don't let me discourage you from continuing to submit ideas, and feel free to reopen if necessary.
