### ISSUE TITLE
rationale for disabling security cache when using only JWT auth

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/security#2034]
the documentation states that the security cache should be disabled when only JWT auth is used:

> If JSON web tokens are the only authentication method that you use, disable the user cache by setting `plugins.security.cache.ttl_minutes: 0`.

see https://github.com/opensearch-project/documentation-website/blob/5d5729c4c00d15b7c3d3204038cf49a5ed48e2aa/_security-plugin/configuration/configuration.md?plain=1#L277-L278

what is the rationale behind this? this is neither specified in the documentation nor could i find anything in this repository.

**Comment by peternied** [comment]
@cwperks Could you provide guidance on this documentation and create a bug/PR to include it in our documentation website?

**Comment by cliu123** [comment]
The cache speeds up authorization based on LDAP or internal database as it avoids fetching roles every time. JWT-based authorization does not need cache as the roles are provided in the JWT.
@opensearch-project/transfer-request Please update the documentation with more details per users request. Thanks!

**Comment by cwperks** [comment]
@rursprung See @nibix' in depth description of the cache.

> The purpose of this cache is to speed up authentication. Authentication
can be quite slow if authentication backends are involved - such as an
active directory server. An authentication round trip with an active
directory server can take well above 100 ms. Without this cache, this
overhead would be added to *each* response coming from OpenSearch.
Applications which need low latency (such as Dashboards) would severely
degraded by that.
>
> Thus, the cache is a map from credentials to authenticated user data. If
credentials of a user are cached, the authentication backend is bypassed
completely.
>
> On the other hand, JWT authentication does usually not require any
roundtrip to an authentication backend, as the authentication is just
done locally using a cryptographic public key. Thus, JWT authentication
is quite fast and usually does not require a cache.
>
> This might be the reason why the docs recommend to switch off the cache
(which is effectively caused by setting ttl 0).
>
> Having said that:
>
> The OpenSearch authentication code also has a special case for these:
>
> https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/auth/BackendRegistry.java#L481
>
> In case no authentication backend is configured, the cache is by-passed.
So, it might be actually possible that the advice in the docs is
actually completely redundant. However, to verify this by 100%, one
probably does need to quickly debug through the code to check whether
the behaviour would be actually equivalent.

I ran a cluster with the JWT Configuration from the docs (i.e. `noop` backend and no authorizers) and as @Nibix pointed out it does not appear to use the cache. I believe this line can be removed from the documentation website.

**Comment by rursprung** [comment]
thanks a lot for the detailed clarification @nibix & @cwperks ❤️

**Comment by cwperks** [comment]
@cwillum I think this would be good to transfer to the [Documentation Website](https://github.com/opensearch-project/documentation-website) repo to determine if anything should be changed regarding documentation. There is a line in the security configuration that states that the user cache should be disabled if JWT auth is the only authentication method used. While it is safe to disable the user cache, its also not necessary as the cache is never used in this configuration. I believe this line can be safely removed, but I also noticed that its the only instance in the documentation where you can find the setting (`plugins.security.cache.ttl_minutes`). Perhaps we should find another place to mention the setting?

**Comment by cwillum** [comment]
@cwperks Yes, I understand the rationale for removing the note from the "Backend configuration" page. Seems unnecessary to set "ttl = 0" if the system bypasses cache when no backend is configured anyhow. I'll create a new issue for the docs repo, remove this guidance from the Backend config page, and add a definition for the `plugins.security.cache.ttl_minutes` property to `opensearch.yml` in the "YAML files" section of documentation. 
By the way, we have a security API that [flushes cache](https://opensearch.org/docs/latest/security-plugin/access-control/api/#flush-cache). Apparently that deletes user, authentication, and authorization cache for the security plugin. The note in `opensearch-project/security/config/opensearch.yml.example` says that the `plugins.security.cache.ttl_minutes` property specifies "Authentication cache timeout in minutes". I'm guessing this is generalizing and includes user and authorization cache, too. Correct me if I'm wrong. Thanks.
