### ISSUE TITLE
[BUG] Opensearch 2.x (with security enabled) does not work with istio

### ISSUE THREAD

**Issue by aggarwalShivani** [opensearch-project/security#2036]
**What is the bug?**
Background:

- We use Opensearch in kubernetes environment with istio handling the mtls (pod-to-pod TLS communication).
- Istio integration was achieved by disabling SSL for Opensearch on the REST layer by disabling the parameter  plugins.security.ssl.http.enabled.  SSL was only enabled for the transport layer and the port 9300 was excluded from istio envoy redirection. 
- So a client application pod in the istio mesh could contact opensearch REST APIs (9200) on HTTP  ( for ex. curl http://opensearch:9200 -u admin:admin), where the Opensearch-security would handle the authentication/authorization of the request, while istio would manage the tls for the traffic between these pods.

Issue: 
With opensearch 2.x, the config parameter plugins.security.ssl.http.enabled setting cannot be disabled due to change made in securitadmin design (i.e. removal of Transport client authorization). 
On disabling this parameter, securityadmin fails with error as explained in https://github.com/opensearch-project/security/issues/1952 

As we cannot disable SSL for the REST (9200) layer for Opensearch 2.x, it no longer works with istio mtls.
The istio functionality worked well with Opensearch 1.x and it is now broken with 2.x. 

**What is the expected behavior?**
Istio integration with Opensearch 2.x to work.

**What is your host/environment?**
 Version 
 - OpenSearch version: 2.1.0
 - OpenSearch-security plugin version: 2.1.0.0

**Comment by peternied** [comment]
@jimishs Can you look into this issue?

**Comment by DarshitChanpura** [comment]
Hey @aggarwalShivani As you mentioned, it is by design that the ability to make remote calls using Transport layer was removed, which leaves REST layer as the only means for communication and so SSL **is required** to be enabled for HTTP calls. Hope this answers your question.

**Comment by jimishs** [comment]
Hey @aggarwalShivani . Thanks for bringing this to our attention. To add to what @DarshitChanpura already said, for security reasons, the administrative remote calls are required to be authenticated using TLS. The SecurityAdmin tool depends on TLS to authenticate its requests in OpenSearch 1.0.0. In OpenSearch 2.0.0+ this has been changed to a single interface (due to removal of Transport layer for authorization). This leaves us with only the REST layer, which is now being used by the SecurityAdmin tool to operate securely. 

We would be interested to hear any ideas on how to securely support this scenario.

**Comment by peternied** [comment]
[Triage] Closing out this issue as there is no action to take at this time.
