### ISSUE TITLE
[FEATURE] Interface suggestions from exploration 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#2089]
**Is your feature request related to a problem?**
It would be nice if we could implement several features or make their use more user-friendly. Specifically: 
1) I think all users should be able to visualize and create a demo dashboard with the test data (airline etc.)--I understand that we do not want to allow permissions across all users but perhaps we can flag the permissions for access of the test data. 
2) Currently, the 403s for trying to access plug-ins you do not have permission for are visibly thrown on the screen, I would recommended a subtler approach i.e. "Oops, it seems like we cannot process your request right now. Please contact your administrator to see if this is a permission issue."
3) Non-admin roles should be able to request roles/permissions notifying the administrator account (this should also be disable-able to avoid request spam at huge operations)
4) I think it would be nice to be able to add backend roles with a drop-down autofill menu. Right now it is not super convenient to move through the permissions. This may not be a great solution in situations with tons of backend roles but I still think it is more convenient then just combing through backend roles. Perhaps show closest-5 regex matches. 
5) Finally, I think it would be a good idea for the administrator to assign permissions/actions groups through the permissions tab. We already have the drop down menu with edit etc., it makes sense to me to be able to just assign "user_x, user_y, user_z" to "action_group_1" when I create the action group. 

**What solution would you like?**
I do not know if this is the result of me being unfamiliar with the intricacies of OpenSearch but hopefully, I/we can work on some of these changes over time to provide a more customer/user friendly experience. 

**What alternatives have you considered?**
As things stand, I think we would be well suited to have more explanatory tooltips. I am sure experts would have no issue with the current interface but as a new user, I can imagine a little bit of confusion. 

**Do you have any additional context?**
This is my first time interacting with the OpenSearch dashboard and I recognize that I may lack some of the context & background knowledge of others. 

I also know some of these requests are pretty-frontend based but I am not sure who these thoughts would fall under.

Thank you everyone :)!

**Comment by RyanL1997** [comment]
@scrawfor99 Thank you for filing this. @peternied Could you please follow up on this?

**Comment by peternied** [comment]
@scrawfor99 Thanks for filing, it looks like almost all of these issues apply to [security-dashboards-plugin](https://github.com/opensearch-project/security-dashboards-plugin) so they might be better suited if the issue was over there.

As it stands we don't have a good way to process this issue as it is.  We try to work through discrete issues towards a goal, sometimes you'll see 'Meta' issues that are used to track particular workflows around a theme; however I don't think that applies in this case.

I noticed that some issues you mentioned such as #3 are more of a feature ask - you might want to use the feature request template instead of a bug template for that one.

I think you'll get the quickest response on these individual issues if you were to file those listed 1..5 in their own issues, would you might reorganizing them as individual issues in the security-dashboards-plugin project?
