### ISSUE TITLE
BadCredentialsException: The token cannot be accepted yet

### ISSUE THREAD

**Issue by AndreaPQ** [opensearch-project/security#2439]
Description:
The current JWT validation process does not account for a time window for the "not before" (nbf) claim. This can cause authentication issues when there is a slight time difference between token generation and validation systems (few seconds).

Solution:
Add a configurable time window (in seconds) for nbf claim validation to allow for slight time differences. This will ensure that the user is authenticated even if the time difference is within the specified window.

actually the  clockOffset used is zero 
JwtUtils.validateJwtNotBefore(claims, 0, false); 

https://github.com/opensearch-project/security/blob/07cf4bb5166733f89cc8454d244fc2d4ffc81a4e/src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/JwtVerifier.java#L112

**Comment by cwperks** [comment]
[Triage] @AndreaPQ Can you please provide some more details about the setup and what you envision for the configuration for this setting? Why is the nbf claim in the future and not valid upon successful authentication?

**Comment by AndreaPQ** [comment]
Hi @cwperks ,it is not uncommon for the system that issues the token or the one that receives it to have system time not synchronized by a few seconds. 
In my case, the openid system that issued the idtoken and populated the nbf claim with the issuance time had an incorrect time that was 5 seconds ahead. 
When opensearch received the token before those 5 seconds had elapsed and validated it, it was deemed invalid as it was not yet valid.

To address this issue, I suggest adding a configurable time window (in seconds) for nbf claim validation to allow for slight time differences. This can be done by modifying the clockOffset parameter used in JwtUtils.validateJwtNotBefore to the desired value. This will ensure that the user is authenticated even if there is a slight time difference between token generation and validation systems.

**Comment by LucaBlackDragon** [comment]
I've faced this sort of issues too in the past.
In my case, due to VM management issues out of my control, our OIDC server clock sometimes fell behind or went ahead of UTC time by a few seconds.
Allowing Opensearch to tolerate a configurable clock skew when validating the `nbf` or `exp` claims of tokens would be a life-saver in such cases (and offering this possibility is quite common in such systems, as far as I know).

**Comment by scrawfor99** [comment]
Hi @AndreaPQ and @LucaBlackDragon, thank you both for providing more information on the issue. You explanations clarify why this change is needed. It sounds like @AndreaPQ has a pretty good understanding of how the change should be made. I would encourage you to open a PR for review so that we can get your fix in as quickly as possible. Thank you.
