### ISSUE TITLE
Nodesdn and Allowlist API allowed only for super admin

### ISSUE THREAD

**Issue by saketmht** [opensearch-project/security#2699]
I am trying to configure the nodesdn via the API on the dashboards but its giving me an error:
```
{
  "status" : "FORBIDDEN",
  "message" : "API allowed only for super admin."
}
```
I have already added `plugins.security.nodes_dn_dynamic_config_enabled: true` in the opensearch.yml as the [docs](https://opensearch.org/docs/latest/security/access-control/api/#distinguished-names) suggest. And I am logged in as the admin user which has the `all_access` role mapped to it. I have `admin` in the CN for admin_dn as well.
`plugins.security.authcz.admin_dn: ["CN=admin,OU=vz-os-cluster"]`

So what exactly is the issue here? Is the super admin different from the one configured in admin_dn? If so, how do I access the API as super admin or make admin have same permissions as super admin?

opensearch.yml file:
```
plugins.security.audit.type: internal_opensearch
plugins.security.authcz.admin_dn: ["CN=admin,OU=vz-os-cluster"]
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn: ["CN=vz-os-cluster,OU=vz-os-cluster"]
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
plugins.security.nodes_dn_dynamic_config_enabled: true
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: tls-http/tls.crt
plugins.security.ssl.http.pemkey_filepath: tls-http/tls.key
plugins.security.ssl.http.pemtrustedcas_filepath: tls-http/ca.crt
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.pemcert_filepath: tls-transport/tls.crt
plugins.security.ssl.transport.pemkey_filepath: tls-transport/tls.key
plugins.security.ssl.transport.pemtrustedcas_filepath: tls-transport/ca.crt
plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".opendistro-alerting-config",".opendistro-alerting-alert*",".opendistro-anomaly-results*",".opendistro-anomaly-detector*",".opendistro-anomaly-checkpoints",".opendistro-anomaly-detection-state",".opendistro-reports-*",".opendistro-notifications-*",".opendistro-notebooks",".opensearch-observability",".opendistro-asynchronous-search-response*",".replication-metadata-store"]

```

**Comment by scrawfor99** [comment]
[Triage] Hi @saketmht, thank you for taking the time to file this issue. Here are some things we are working towards that may address your issue:

1. In the short-term you can make this request by using the "super admin" `admin_cert` as part of your request chain. This will allow you to execute your requests.
2. In order to help users like yourself, we are in the process of making these "super admin" privileges grantable via the regular API. This feature should be expected in an upcoming minor version release. 

I am closing this issue since we already have a couple plans in the works for your feature. However, if you have any further comments on this please do not hesitate to reach out.
