### ISSUE TITLE
[Maintenance] FGAC API should ignore extra whitespaces in configuration such as backend roles

### ISSUE THREAD

**Issue by stephen-crawford** [opensearch-project/security#2702]
As a part of general guidelines around the codebase, we need to validate that all APIs and field input values are compliant and consistent with the other OpenSearch API field input values (eg: https://unicode.org/reports/tr29/#Default_Sentence_Boundaries). 

Completion of this issue will look like a PR which corrects any instances of the improper API format being used. If no instances are found, verification of the code base should be logged as a dummy PR which will be merged and represent the sign-off of the correct state. 

If it is too complicated to include all changes in a single PR, it is appropriate to use this issue as a tracker and link out various related PRs from here. In this case, completion of the issue would take the form of a completed checklist documenting the linked PRs introducing smaller changes.

**Comment by nibix** [comment]
@scrawfor99 You mention "general guidelines around the codebase". Do you have a pointer to these guidelines?

Some questions which come to my mind:

- Are  we talking about APIs which are provided by the security plugin or about APIs which are consumed by the security plugin?
- Most APIs are probably JSON based. Is this about whitespace in the JSON document (which I believe is handled by the JSON parser) or about whitespaces inside the attribute values defined in the JSON document.
- Ignoring whitespace which was not ignored before will be a breaking change in many cases. How are the requirements for backwards compatibility?

**Comment by scrawfor99** [comment]
Hi @nibix, I just used that phrasing to refer to consistency with the rest of the API and field input values. You raised some good questions which I am going to defer to @davidlago about since I don't think I can give an authoritative answer to what he had in mind. 

Tentatively, I would say we are looking at APIs provided by the Security Plugin; whitespace inside the values per https://unicode.org/reports/tr29/#Word_Boundaries; finally, backwards compatibility should be maintained since we only want to remove whiteaspace inclusion in fields where it was previously failing to properly handle extra whitespaces. I believe we should only be changing behavior in cases where we were incorrectly handling fields with whitespaces. So the behavior was not consistent with the expected behavior. 

Dave should be able to clarify these details for you.
