### ISSUE TITLE
[BUG] Version and Legacy Change in Core Breaks Build

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#2727]
**What is the bug?**
This change in [core](https://github.com/opensearch-project/OpenSearch/commit/142ae4611042669c9511a81a014828ca22376afc) moves the Version and LegacyESVersion classes from the server module
to the core library. This causes a build failure where either is used. 

Need to refactor to adjust for the changes.

**Comment by scrawfor99** [comment]
[Triage] @peternied is fixing currently.

**Comment by peternied** [comment]
@scrawfor99 Thanks for proactively creating this issue, we don't need to take any action since the package of Version is still the same, only [FileSystemUtils.java](https://github.com/opensearch-project/OpenSearch/commit/142ae4611042669c9511a81a014828ca22376afc#diff-1dcd62572411ee7879d6b7f06e072814578d3ebb4704dd4dcbc88307462027ac) was modified and there are no references to it in our codebase
