### ISSUE TITLE
[BUG] Backward compatibility tests failing for security plugin

### ISSUE THREAD

**Issue by parasjain1** [opensearch-project/security#2950]
**What is the bug?**
Backward compatibility tests are failing for security plugin on the main branch which impacts the release quality and prevents us from catching any regressions / bugs that might creep.

**How can one reproduce the bug?**
Attaching recent PRs -
- https://github.com/opensearch-project/security/pull/2802
- https://github.com/opensearch-project/security/pull/2937

**What is the expected behavior?**
Backward Compatibility tests should be passing in GitHub actions.

**What is your host/environment?**
N/A

**Do you have any screenshots?**

**Do you have any additional context?**
Tests seem to be failing due to a dependency conflict
```
* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > Conflict(s) found for the following module(s):
       - org.apache.httpcomponents:httpclient between versions 4.5.14 and 4.5.13
     Run with:
         --scan or
         :dependencyInsight --configuration compileClasspath --dependency org.apache.httpcomponents:httpclient
     to get more insight on how to solve the conflict.
```

**Comment by parasjain1** [comment]
Raised PR for the fix - https://github.com/opensearch-project/security/pull/2951

**Comment by cwperks** [comment]
@parasjain1 I just opened a separate [PR against the 2.x branch](https://github.com/opensearch-project/security/pull/2952). I think the issue is that 2.x is explicitly referring to 4.5.13 and should instead take the [version of httpclient from core's buildSrc/version.properties](https://github.com/opensearch-project/OpenSearch/blob/2.x/buildSrc/version.properties#L34)

**Comment by cwperks** [comment]
@parasjain1 I just noticed that the head of 2.x had other compilation issues due to a [backport of a refactor in core](https://github.com/opensearch-project/OpenSearch/pull/8460)

I have raised a PR to both address the core refactor and the bwc issue: https://github.com/opensearch-project/security/pull/2953

**Comment by cwperks** [comment]
This is now resolved. Closing this issue.

**Comment by parasjain1** [comment]
Thanks Craig.
