### ISSUE TITLE
[BUG] Somehow security plugin rewrites permissions for other plugins which use Bouncy Castle

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/security#3213]
**What is the bug?**

Use case: 
2 plugins which use BC.`OpenSearch` starts plugins on the node in the alphabetic order.
The plugin  which starts first uses right permissions for PC to execute its operations. 
After the sec plugin started  permissions changed as result the first plugin can't use its permissions. 

**What is the expected behavior?**
Permissions should not be changed. 

**What is your host/environment?**
 - OS: 2.9 only

**Comment by scrawfor99** [comment]
[Triage] Hi @willyborankin, thank you for filing this issue. The first step to addressing this issue may be determining a mitigation strategy based on the potential for the Security plugin to restrict other components. Seems the first item for this issue will be determining the extent of the issue and whether we can work around the problem. Leaving untriaged pending actionable tasks--but for the interim this will require diagnosis.

**Comment by peternied** [comment]
Could be related to the recent bump in the plugin policy?
- https://github.com/opensearch-project/security/pull/2901

**Comment by willyborankin** [comment]
Reproduced it with 1.3.12 something is on OS side

**Comment by reta** [comment]
The problem seems in general unsolvable if relying on `Security.addProvider`. As one option, the `security` plugin may widen up the permissions that are required by `BouncyCastle`, for example:

```
permission java.security.SecurityPermission "getProperty.org.bouncycastle.*";
```

It may partially solve the issue.

**Comment by cwperks** [comment]
@willyborankin could the JJWT issue experienced on 2.x be the same problem here? 

We made a PR to wrap the call to create the JJWT JwtParser with `AccessController.doPrivileged(...)` because there was a permissions issue: https://github.com/opensearch-project/security/pull/3189

It was complaining it couldn't find the following permission:

```
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")
```

but this permission is defined in the `plugin-security.policy` file [here](https://github.com/opensearch-project/security/blob/2.x/plugin-security.policy#L32). If it's granted in the policy file, then is that policy not being taken into effect somehow?

Recapping the permissions issues we've seen recently:

- Permissions issue on OpenSAML upgrade to 4.3.0 which was fixed in this PR: https://github.com/opensearch-project/security/pull/2987
- Permissions issue after upgrade to JJWT 0.11.x: https://github.com/opensearch-project/security/pull/3189

**Comment by willyborankin** [comment]
@cwperks Yes looks closer. I took a look in JJWT `DefaultJwtParserBuilder` it uses `ServiceLoader` which is ok. I'm wandering what was changed in OS.

**Comment by reta** [comment]
@cwperks I think these issues are unrelated:
 - Jwt needed `AccessController.doPrivileged`  (you fixed that)
 - Saml needs to use `Cleaner.create(<thread factory>)` instead of `Cleaner.create()` so we could provide the one OS managed one (will be looking into that with @willyborankin )

**Comment by peternied** [comment]
[Triage] @reta could you provide details on what next steps look like for this issue?

**Comment by scrawfor99** [comment]
[Triage] Resolved by https://github.com/opensearch-project/security/pull/3289.
