### ISSUE TITLE
Support Multiple SAML Domain 

### ISSUE THREAD

**Issue by xikunyu** [opensearch-project/security#3377]
**Is your feature request related to a problem? Please describe.**
We have multiple saml domains. Can opensearch support multiple saml domain?

**Comment by scrawfor99** [comment]
Hi @xikunyu, thank you for filing this issue. At this time, OpenSearch cannot support multiple SAML domains. There are no current plans to add this functionality directly. Instead you can use the the multi auth provider in order to support multiple forms of authentication but we do not plan to support multiple instances of SAML domains for a single domain. If you would like to open a separate issue as a RFC providing an argument for this case please do so. Thank you.
