### ISSUE TITLE
[FEATURE] Set baseline JDK version to JDK-21

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/security#3609]
**Is your feature request related to a problem?**
To finally rid off Apache HTTP 4.x we need to bump OpenSAML to version 5.0 which does not work with JDK 11 since the baseline for it is JDK 17. An attempt was done in this PR [1] without success since all JDK 11 jobs failed.

- [1] https://github.com/opensearch-project/security/pull/3603

**Comment by scrawfor99** [comment]
[Triage] This issue is part of the larger effort to bump the default version. Closure criteria for this issue would be completely upgrading the default version as suggested. I have attached the associated proposal from core below. 

Here is an associated proposal in core: https://github.com/opensearch-project/OpenSearch/issues/10745

**Comment by reta** [comment]
Apache Lucene 10 just went with JDK-21 baseline, so I've refhected that

**Comment by reta** [comment]
Closed by https://github.com/opensearch-project/security/pull/4457
