### ISSUE TITLE
customize kibana.index ,console log is not reasonable

### ISSUE THREAD

**Issue by lixunhuan** [opensearch-project/security#366]
version: odfe 1.6.0
make config in kibana
server.name: kibana
server.host: "0"
elasticsearch.hosts: https://localhost:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: admin
elasticsearch.password: admin
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
kibana.index: ".kibanayg"
opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]

newsfeed.enabled: false
telemetry.optIn: false
telemetry.enabled: false

console log:
{"type":"error","@timestamp":"2020-04-09T07:14:58Z","tags":["error","migration"],"pid":1,"level":"error","error":{"message":"Authorization Exception: Authorization Exception","name":"Error","stack":"Error: Authorization Exception: Authorization Exception\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4929:19)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"message":"Authorization Exception: Authorization Exception"}
{"type":"log","@timestamp":"2020-04-09T07:14:58Z","tags":["status","plugin:opendistro_security@1.6.0.0","info"],"pid":1,"state":"yellow","message":"Status changed from yellow to yellow - Tenant indices migration failed","prevState":"yellow","prevMsg":"Setting up index template."}

**Comment by palashhedau** [comment]
The console message is not clear.

Can you turn on the verbose and provide the information here.

Not sure, but it seems like this is the issue with kibana username. 
https://github.com/opendistro-for-elasticsearch/security/blob/825863b5f617c7a191e5ee8d25b88bf1df6d9bbc/src/main/java/com/amazon/opendistroforelasticsearch/security/rest/TenantInfoAction.java#L94


Can you check if the kibana username in elasticsearch is same as configured in kibana.yml?
If not the issue is expected. 
You can use this API to find the kibana username in elasticsearch - 
curl https://localhost:9200/_opendistro/_security/api/securityconfig?pretty

part of output 
` "kibana" : {
        "multitenancy_enabled" : true,
        "server_username" : "kibanaserver",
        "index" : ".kibana"
      },`

Please let me know if helps.

**Comment by davidlago** [comment]
Closing unable to reproduce given the information above. Please feel free to re-open if this is still an issue in current versions of OpenSearch. Thanks!
