### ISSUE TITLE
role_mapping :  setup  to "AND" between backend username and role backend conditions

### ISSUE THREAD

**Issue by Rymev** [opensearch-project/security#367]
Hello,

I'm using the security plugin and I have questions about role mapping. 

As far I understood, in order to associate users and specific rights I have three way :
- Using user name
- Using backend role
- Using hostname

I'm using an IDP (keycloak) with an openid connexion and I did managed to authenticate with user name or backend role.

My problem is : when a user come with a matching backend role OR matching user name, the plugins grant rights. Is it possible to setup the plugin to grant rights only if backend role AND user name are matching?

Also I didn't find much informations about hostname authentification. As I understand, it check the host where the connexion request come from.

I'm using a kibana, and my authentification is delegated to a n IDP. Will my hostname be kibana's one or the IDP's one ?

Thank you.

**Comment by dinusX** [comment]
Hi Rymev,

Based on current plugin configuration it is not possible.

Could you describe why would you want to have an "AND" condition between both ? Why "OR" is not working for your use-case?

Instead of having an "AND" condition, you could probably grant roles solely based on "backend_role", which means that you should not have any users mentioned in the role mapping at all.

Regarding your question related to the hostname authenticator: that authenticator basically tells that if you access Kibana & ES from X address, you'll be granted automatically the roles mapped to the following X address.

**Comment by nateynateynate** [comment]
Hi @Rymev  - did @dinusX 's suggestion help you at all? You may want to reiterate your question in the OpenSearch forums (https://discuss.opendistrocommunity.dev/) as well.  If you can, see if the behavior is any different using the latest OpenSearch and OpenSearch Dashboards. Going to close - feel free to reopen if needed.
