### ISSUE TITLE
disable TLS for Transport, enable for Rest

### ISSUE THREAD

**Issue by nean-and-i** [opensearch-project/security#37]
Is it possible to disable encryption for node-to-node transport but have encryption for REST Layer ?

like to set _false_ for `opendistro_security.ssl.transport.enabled` (and comment/disable  `opendistro_security.ssl.transport.*`), 
and keep _true_ for `opendistro_security.ssl.http.enabled`

unfortunately I get 
`Caused by: java.lang.IllegalStateException: opendistro_security.ssl.transport.enabled must be set to 'true'
`

if security enabled on both, everything works fine.
do I miss something?

thanks

**Comment by abhijithshivaswamy** [comment]
I think you cannot disable Transport SSL as of now, i have opened a issue for the same
https://github.com/opendistro-for-elasticsearch/security/issues/36

Possible Duplicate of #36

**Comment by hardik-k-shah** [comment]
Inter node request carries user context (which contains sensitive information like user credential details, roles etc..), hence for securing user's sensitive information we need to enable node to node encryption. 

So, it is not possible to disable SSL at transport layer.  

Duplicate of https://github.com/opendistro-for-elasticsearch/security/issues/36

**Comment by nean-and-i** [comment]
@hardik-k-shah , understood, but this depends on the design I'd say.
The transport can happen within a data dmz where the traffic is not exposed and the only way to get data in is ingest in front of it and coordinating nodes ,so in this case I'd need encryption on REST layer only.

ingest -> node1-node2-...nodeN -> coordinating node

so, if there is no chance to get this integrated it might be worth to remove that from the documentation and config examples.

**Comment by JulienCarnec** [comment]
I agree that this would be very convenient in topologies residing in DMZ.
+1

**Comment by alolita** [comment]
Hi @nean-and-i @JulienCarnec - Thanks for raising this use case. Can you provide details about scenarios that exist for you in a single DMZ. Currently transport SSL cannot be disabled. Keeping this as an action item to investigate further.

**Comment by abhijithshivaswamy** [comment]
@alolita , we have ES cluster in a VPC, with Kibana behind a HTTPS Proxy, we use ODFE for Logs, Analytics and Alerting. We do not required HTTPS or Node-to-Node encryption.

**Comment by JulienCarnec** [comment]
Hi @alolita ,
In our use-case we use ODFE inside a secured Kubernetes cluster.

**Comment by nean-and-i** [comment]
Hi @alolita ,
I'm using an EL cluster in one of our datacenters where I have dedicated ingest nodes for inserting data into the cluster and on the other hand I also have dedicated coordinator nodes for queries.
The data nodes are in a dedicated not exposed vlan, so only ingest and coordinator nodes are able to access the data nodes via a dedicated backend connection into the vlan.
So everything is separated and there is no chance to access/sniff the transport traffic.
This means there are reasonable examples/design/architecture where transport and rest is separated, hence it could make sense to separate encryption.
I was thinking of avoiding as much additional processing as possible, I want to go for as low latencies as possible on the cluster and saturating its 10G interlinks.

**Comment by jhammons** [comment]
I too wish to disable TLS for transport.

**Comment by philipp1992** [comment]
#metoo

**Comment by daskanu** [comment]
#metoo

**Comment by Atreus-Technologies** [comment]
Another request for this here... We really only have a need for the authentication backends (LDAP, OIDC et al.) and no need for any encryption support.

There are really a few sets of different functionality in this plugin that ought to be individually available, (1) encryption (transport and REST layers), (2) authc and (3) authz. 

This issue is even more pressing given that ES's official ECK K8s operator enforces the use of SSL via xpack. With this plugin also forcing its own SSL on the transport layer I imagine there are going to be conflicts, which may prevent the use of this plugin with the official ECK operator (although I am still poking around to find a workaround for this).

**Comment by eljohnson92** [comment]
I am trying to use this plugin in a kubernetes cluster with a service mesh which is already taking care of inter-node secure communication and would also like to turn this off

**Comment by NickDatLe** [comment]
Same here, I am running k8s istio service mesh with mTLS in STRICT mode. I would to turn TLS off.

**Comment by publicvirtualvoid** [comment]
Appreciate that you'd like to enforce sound security practises, but in the age of microservices... terminating TLS is not OFFE's job.

**Comment by SKumarMN** [comment]
@hardik-k-shah  what is the product management thoughts about this request. Is this planned to be implemented or there is no plan for this now?

**Comment by dmpe** [comment]
I am also facing same issue. We are running a security k8s cluster and it is not that easy to generate correct certs for internode/interpod communication. 
Removing the requirement to use TLS communication, but still keeping other security features, would be very much welcoming feature.

**Comment by dmpe** [comment]
Ok, I can report some progress for those who want to use this security plugin but are currently unable due to various reasons, eg. related to certs and/or kubernetes. 
Basically, the solution is to heavely adjust helm chart:
-  remove data & master node and use just a client node which gets two additional roles (of being data and master) -> https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/opendistro-es/templates/elasticsearch/es-client-deploy.yaml#L81
-  because we use traefik as ingress provider (its `ingressroute`), client's ingress has to be adjusted as well. -> https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/opendistro-es/templates/elasticsearch/es-client-ingress.yaml
-  becasue, your ES client becomes master and data node at the same time, you will need to ensure that you expose a correct set of services -> https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/opendistro-es/templates/elasticsearch/es-service.yaml
- the strategy is then doing following: you expose ES on a ("public") ingress, e.g. `elastic.devops.firm.com` and do the same with kibana (with its security plugin) which points to that  `httpS://elastic.devops.firm.com`. We run them both fine now, from 1 cluster, and ES is protected by default with password admin:admin which you can change. Same goes to kibana.

This is by no means optimal because in principle if you have just large cluster (we have just minikube) you dont need to expose ES via ingress. But doing so, puts ES on SSL and kibana is then quite easy for lift off. 
Unfortunately, I am not able to post code here but that should help some people, until this issue will get higher priority in the roadmap. 💯 (which i hope it will)

**Comment by Atreus-Technologies** [comment]
@dmpe, this issue is not related to helm charts or K8s. It requests an option to disable TLS at the transport layer in Opendistro. It is not related to Traefik, Helm deployments, Minikube, or other aspects of a K8s setup.

Can you please edit your comment to make it clear that it does not resolve the issue, or (better!) delete your comment here and create a new issue describing your workaround?

While it may help some users, I am concerned your comment implies that there is a workaround. This might lead to premature closure of the issue (if the maintainers actually checked their Github issues, which I suspect they do not, but still...)

Happy to provide you some advice on your setup for  if you want to dm me @MilesGarnsey on Twitter.

**Comment by hardik-k-shah** [comment]
Sorry for the delay! 
We will bring this to our next prioritization meeting and update here soon.

**Comment by NickDatLe** [comment]
hey @hardik-k-shah - do you have an ETA of when the update of when we would be able to turn off inter-node TLS through elasticsearch.yml?

**Comment by hardik-k-shah** [comment]
Hello all,

Yes, we have discussed this issue internally and decided that for benefit of ODFE community, we will be supporting configuration to disable TLS. (Though we strongly recommend not to disable TLS).

And we are currently testing TLS disabling feature. 
Same time we are also working on introducing Dual Mode (so moving from TLS disable to enable will become simpler without down time. )

Thank you all.

**Comment by lukasmrtvy** [comment]
@hardik-k-shah will it be available in next release ? 1.10.1 ? thanks

**Comment by spapadop** [comment]
I've brought this issue up in the meetup couple of weeks ago but didn't get any response yet. 
I do not see this into the current [roadmap](https://github.com/orgs/opendistro-for-elasticsearch/projects/3) either. Is this something that is being worked on, or not yet?

Thanks a lot in advance for any info.

**Comment by stockholmux** [comment]
@spapadop Sorry we missed this one from the community meeting a while ago but I'm checking into it now.

**Comment by spapadop** [comment]
Hi @stockholmux, any info on this one yet?

**Comment by stockholmux** [comment]
@spapadop Working on getting this on our public roadmap.

**Comment by stockholmux** [comment]
@spapadop This is officially on the roadmap.

**Comment by spapadop** [comment]
@hardik-k-shah maybe you have some more insights on this?

**Comment by stockholmux** [comment]
@spapadop Not sure, to be honest. I know the team has been juggled a bit. Let me find out. Maybe @davidlago knows about the mysterious roadmap item?
