### ISSUE TITLE
[BUG] Response content-type changed in 2.11 for some endpoints

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3718]
In 2.11, there was a change to introduce a [SecurityResponse](https://github.com/opensearch-project/security/pull/3430) wrapper around a BytesRestResponse. In the method to cast the SecurityResponse to a RestResponse, the method creates a [BytesRestResponse using the constructor](https://github.com/opensearch-project/security/blob/2.11/src/main/java/org/opensearch/security/filter/SecurityResponse.java#L56) without contentType. (Here's the [BytesResponseResponse constructor](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/rest/BytesRestResponse.java#L78-L83) for context). Even if an instance of [SecurityResponse is created with a Content-Type header](https://github.com/opensearch-project/security/blob/2.11/src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java#L239) it is being ignored since the constructor of BytesRestResponse will set it at the time the RestResponse is instantiated.

APIs impacted:

- `/_plugins/security/api/authtoken`
- Any Unauthed call now responds with `application/json` instead of `text/plain`

**Comment by scrawfor99** [comment]
The [change](https://github.com/opensearch-project/security/blame/1d46ba6131aa1d8994da6eb13965c5d4d5c698df/src/main/java/org/opensearch/security/filter/SecurityResponse.java#L56) to the `SecurityResponse` class causes all of the methods hit with `asRestResponse()` to be converted.

This means that the impacted APIs can be found by moving up a level to where the `asRestResponse()` method is called inside of the `[SecurityRestFilter](https://github.com/opensearch-project/security/blob/1d46ba6131aa1d8994da6eb13965c5d4d5c698df/src/main/java/org/opensearch/security/filter/SecurityRestFilter.java#L132C25-L132C25)`. Then we can look at each of the scenarios inside the `wrap` method to determine which calls are impacted. 

Notably, the `wrap` method is called on _all_ rest requests so it is more about the actual cases and whether they trigger the if-statements that lead to the `asRestResponse` than anything else. 

The [first `asRestResponse`](https://github.com/opensearch-project/security/blob/1d46ba6131aa1d8994da6eb13965c5d4d5c698df/src/main/java/org/opensearch/security/filter/SecurityRestFilter.java#L139C3-L139C3) is called when we try to determine whether the response has been cached. This is then based in the [`SecurityHttpServerTransport`](https://github.com/opensearch-project/security/blob/1d46ba6131aa1d8994da6eb13965c5d4d5c698df/src/main/java/org/opensearch/security/http/SecurityHttpServerTransport.java#L48) logic. Looking at this, it seems that we try to signify early responses for handling of decompression by identifying request attributes which are set in the `[Netty4HttpRequestHeaderVerifier](https://github.com/opensearch-project/security/blob/1d46ba6131aa1d8994da6eb13965c5d4d5c698df/src/main/java/org/opensearch/security/ssl/http/netty/Netty4HttpRequestHeaderVerifier.java#L112)`. 

The [second `asRestResponse`](https://github.com/opensearch-project/security/blob/1d46ba6131aa1d8994da6eb13965c5d4d5c698df/src/main/java/org/opensearch/security/filter/SecurityRestFilter.java#L160) happens when we check whether the request is authenticated and skip any that are not. This covers the scenarios that Craig mentioned above with his second bullet about unauthed calls. 

The [third `asRestResponse`](https://github.com/opensearch-project/security/blob/1d46ba6131aa1d8994da6eb13965c5d4d5c698df/src/main/java/org/opensearch/security/filter/SecurityRestFilter.java#L176C16-L176C16) happens when a request is denied. This is what it sounds like, we check whether a request is not allowlisted (if allowlisting is enabled). We return false if it is not allowlisted and then set this optional which will cause the `asRestResponse` call. 

The [final `asRestResponse`](https://github.com/opensearch-project/security/blob/1d46ba6131aa1d8994da6eb13965c5d4d5c698df/src/main/java/org/opensearch/security/filter/SecurityRestFilter.java#L182) happens when a response is queued for delivery. This occurs when a response is placed in the response queue for a channel based on the `SecurityRequestChannel` interface. If the channel has a queued response we send a response by grabbing the queued response from the channel and calling `asRestResponse` on it.
