### ISSUE TITLE
[FEATURE] Support `external` for authentication_backend where user list is defined in another cluster

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#4175]
**Is your feature request related to a problem?**

When configuring [basic authentication](https://opensearch.org/docs/latest/security/authentication-backends/basic-authc/#the-internal-user-database), the cluster admin must specify an authentication_backend for where to look for the list of users.

```
authentication_backend:
  type: internal
```

Internal in this case refers to the users living internally in the security index of corresponding cluster. 

This feature request is to support `external` for this setting where the user list is defined in another trusted cluster. 

If `external` is defined then this cluster could operate in a sort of primary/replica mode where the each node could populate its cache from the external list of users and would need the primary to notify it about changes to internal users. 

**What solution would you like?**

With [Multiple Datasources](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1388) it may be useful to have one cluster be the primary source for internal users.

**What alternatives have you considered?**

Keep a mirror of all connected data sources

**Do you have any additional context?**

- https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1388

**Comment by peternied** [comment]
I don't think we should add another authentication backend for this scenario.

We support [JWT Web Tokens](https://opensearch.org/docs/latest/security/authentication-backends/jwt/), if this was of great importance adding functionality so that the internal user list can communicate externally via JWT Web Tokens, or another authentication standard (SAML/OIDC).  Making a special AuthN provider seems like more trouble than its worth for a strange use case.

**Comment by scrawfor99** [comment]
[Triage] Hi @cwperks thanks for filing this issue. Based on the comment above and your thumbs up, it seems like there is agreement that using JWTs or something like SAML is an appropriate alternative. Going to close this issue as a result. Thank you!
