### ISSUE TITLE
[FEATURE] Add checklist item that frontend PR is raised for adding new roles/permissions

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security#4330]
**Is your feature request related to a problem?**
There has been a few misses where no corresponding frontend security dashboards plugin PR was raised when adding new roles/permissions. We should at least add a checklist on backend PRs that makes folks aware of this step
**What solution would you like?**
New checklist item raising awareness of frontend changes required
**What alternatives have you considered?**
Enforcing this somehow else, but checklist is a good start
**Do you have any additional context?**

**Comment by varun-lodaya** [comment]
Good call! We should.

**Comment by shikharj05** [comment]
@derek-ho sounds good. However, any new plugin or core can add a new action (and hence a permission) and it won't always need a change in SecurityPlugin backend. Do you think it's possible to consider auto-discovery of actions?

For roles, it should always work, right? since, frontend plugin calls APIs in backend.

**Comment by cwperks** [comment]
[Triage] It's a good idea to add this to the checklist on the security repo to ensure that contributors also update the list of permissions tracked in security-dashboards-plugin.

@derek-ho I have assigned this issue to you. Can you update the [PR template](https://github.com/opensearch-project/security/blob/main/.github/pull_request_template.md)?
