### ISSUE TITLE
Status code for read only resources

### ISSUE THREAD

**Issue by sujithvm** [opensearch-project/security#719]
Currently, if user has correct authentication and authorization to modify an opendistro read-only resource, 403 is returned. 

As per [wiki](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_client_errors) and other resources, most common practice is to return 405 (Method not allowed) 

authentication failure - 401
authorization failure - 403
read only resource failure - 405 

Returning correct status code would differentiate the behavior. 

Any thoughts?

**Comment by vrozov** [comment]
AFAIK, both 403 and 405 status codes are acceptable and widely used when a client tries to modify a read-only resource. Note that 403 status code explicitly allows it to be used for errors not directly related to authorization and ES uses it for read-only resources. I'd suggest continue to use 403, so that we are consistent with ES and don't break REST API backward compatibility.

**Comment by sujithvm** [comment]
>  403 status code explicitly allows it to be used for errors not directly related to authorization

I understand ES has used 403 for some read only index setting (posted in #716) but doesn't its vague definition call for its misuse (readonly context) when there is a more appropriate status code to return?

> don't break REST API backward compatibility.

I wouldn't worry about breaking backward compatibility if it is the correct status to be returned.

**Comment by vrozov** [comment]
It is arguable whether ES usage of 403 (Forbidden) should be qualified as misuse. Forbidden in this case means that writes are not allowed (for whatever reason). 405 (Method not allowed) is mostly used by ES when wrong methods (for example `GET` instead of `PUT`) is used. IMO, in our case it is more important to focus on "read-only" property of the resource (write is forbidden), not that it can be get, but not updated.

Not breaking backward compatibility is an additional benefit, the proper (allowed, expected and consistent) usage of return code is primary.

**Comment by cliu123** [comment]
> s code explicitly al

**Comment by sujithvm** [comment]
The main intent of the issue is to differentiate behavior by returning appropriate status code. How to differentiate the following? Both the following would 403 and will have to rely on response body messages. 
- Having no access to Opendistro APIs to update resources
- Having access to Opendistro APIs but modifying a read-only resource.

**Comment by vrozov** [comment]
This will not solve the issue as now it will not be possible to distinguish status code for read-only resources and wrong method used (for example POST instead of PUT).

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
